from fpdf import FPDF
from datetime import datetime

class CareReportPDF(FPDF):
    def header(self):
        # Hospital / Project Branding
        self.set_font("Arial", "B", 15)
        self.set_text_color(40, 70, 160)
        self.cell(0, 10, "Clinical Care Coordination Report", ln=True, align="C")
        self.set_draw_color(40, 70, 160)
        self.line(10, 22, 200, 22)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AI Care Assistant", align="C")

def create_pdf(report_data):
    """
    Takes the 'final_report' dict from the LangGraph agent and generates a PDF.
    """
    pdf = CareReportPDF()
    pdf.add_page()
    
    # 1. Basic Information
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, f"Report Date: {report_data.get('generated_at', 'N/A')}", ln=True)
    
    # 2. Risk Status Highlight
    risk_level = report_data.get("risk_level", "Unknown")
    pdf.set_fill_color(255, 200, 200) if "High" in risk_level else pdf.set_fill_color(200, 255, 200)
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 12, f"Patient Risk Status: {risk_level} ({report_data.get('risk_score')})", ln=True, align="C", fill=True)
    pdf.ln(5)

    # 3. Patient Summary Table
    pdf.set_font("Arial", "B", 11)
    pdf.cell(0, 10, "Patient Summary:", ln=True)
    pdf.set_font("Arial", "", 10)
    summary = report_data.get("patient_summary", {})
    details = [
        f"Age: {summary.get('age')}",
        f"Gender: {summary.get('gender')}",
        f"Wait Time: {summary.get('wait_days')} days",
        f"Known Conditions: {', '.join(summary.get('conditions', [])) if summary.get('conditions') else 'None'}"
    ]
    for detail in details:
        pdf.cell(0, 7, f"- {detail}", ln=True)
    pdf.ln(5)

    # 4. Risk Analysis Section
    pdf.set_font("Arial", "B", 11)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "AI Risk Analysis:", ln=True, fill=True)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 7, report_data.get("risk_analysis", "N/A"))
    pdf.ln(5)

    # 5. Intervention Plan Section
    pdf.set_font("Arial", "B", 11)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "Recommended Intervention Plan:", ln=True, fill=True)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(0, 7, report_data.get("intervention_plan", "N/A"))
    pdf.ln(10)

    # 6. Disclaimer (Stripping Unicode characters like emojis for font compatibility)
    pdf.set_font("Arial", "I", 9)
    pdf.set_text_color(150, 0, 0)
    # The standard Helvetica font does not support the medical emoji '⚕'
    clean_disclaimer = report_data.get("disclaimer", "").replace("⚕️ ", "DISCLAIMER: ")
    pdf.multi_cell(0, 6, clean_disclaimer)

    return bytes(pdf.output()) # Return as bytes for Streamlit